"""Offline tests against the committed jmap/cpp fixture - no network, no live clone.

``gatectl`` verifies this card with the network proxied to a dead port (this card's own
``network: false``), so nothing here may reach out; everything is read from the fixture
``run_extraction.py`` already produced and committed at
``tests/fixtures/jmap_cpp/api_surface.json``.

C++-platform extraction support was already proven by the cells/cpp onboarding (after
TC-092's consolidate_classes() fix); this card is a straight run-and-pin against a second,
real, public C++ repository (``aspose-email-foss/Aspose.JMAP-FOSS-for-Cpp``) - no engine
change at all. "cpp" goes through the ordinary tree-sitter path (grammar name literally
``"cpp"``) via ``tree_sitter_engine.api_surface``. Its ``language`` field reads literally
``"cpp"``.

Unlike cells/cpp's nested ``include``/``src`` layout, this real repository is a
header-only library: every real entry's ``file`` ends in ``.hpp`` (none of this fixture's
types live in a ``.cpp`` translation unit), so ``package_root._detect_cpp_root()`` found a
top-level ``include`` directory directly.

The real repository's full public surface is only 39 types - well under the CLI's default
--max-types 300 cap - so this fixture is the complete surface, not a sub-sample:
``type_count == reduced_type_count == 39`` and ``truncated is False``.

The observed ``kind`` vocabulary is ``{"class_specifier", "struct_specifier"}`` - this
repository's public surface has no top-level free functions or enums in the reduced set.

TC-308 re-ran this extraction live (network access, real default --max-types 300, no
``--max-types`` override) now that both TC-252 (centrality-ranked ``reduce_fixture()``) and
TC-261 (``inherited_from`` provenance tagging in ``_flatten_inheritance()``) are on main.
The commit pin (``559c962081323468039dc75cf38676499f32b20e``) and repository
(``aspose-email-foss/Aspose.JMAP-FOSS-for-Cpp``) came back unchanged and match
``infra/helm/foss-mcp/values.yaml`` and ``docker-compose.yml`` exactly - no commit-pin
divergence here, unlike several sibling pilots fixed earlier this session. ``type_count``,
``reduced_type_count``, ``truncated``, and the ``kind`` vocabulary are all unchanged too.

Unlike the jmap/go and cells/rust siblings in this same wave (which turned out to be
genuinely flat - their real upstream has no non-trivial base class to copy members from),
this pilot's real upstream source DOES have genuine, non-trivial inheritance to tag, and the
regeneration closes a real staleness defect: the previously-committed fixture was last
regenerated by TC-232, before TC-261 landed, so it carried real non-empty ``bases`` lists
(``JmapClient``, ``MailClientMixin``, ``SubmissionClientMixin``, ``JmapNetworkError``,
``JmapProtocolError`` all inherit from something real) but exactly zero ``inherited_from``
tags anywhere - confirmed directly against the pre-regeneration fixture before this card ran.
The live re-run adds 35 ``inherited_from`` tags across the fixture's copied methods, zero of
which existed before, with none of the type/kind/commit facts above changing.

This pilot also directly exhibits the multi-level rooting TC-261's own fix specifically
targets: ``JmapClient`` inherits from both ``MailClientMixin`` and ``SubmissionClientMixin``
(each a real, direct base, declared in ``include/aspose_jmap/JmapClient.hpp``), and each of
those mixins itself inherits from ``JmapClientCore`` (``include/aspose_jmap/client_mail.hpp``
and ``include/aspose_jmap/client_submission.hpp``) - a real three-class, two-level chain.
``JmapClient``'s copy of a method ``MailClientMixin`` itself declares (e.g.
``listMailboxes``) correctly roots to ``aspose_jmap::MailClientMixin`` (the real, direct
declaring ancestor), while its copy of a method that originates in ``JmapClientCore`` and was
only copied THROUGH ``MailClientMixin`` (e.g. ``connect``, ``sendRequest``, ``echo``,
``uploadBlob``, ``downloadBlob``) correctly roots to ``aspose_jmap::JmapClientCore`` - the
true, original declaring ancestor - not to ``MailClientMixin``, the intermediate parent it
was transitively copied through. The same holds for the ``SubmissionClientMixin`` branch of
the chain. See ``test_a_real_multilevel_inherited_from_chain_is_correctly_rooted`` below.

A simpler, one-level relationship is also present and asserted:``JmapNetworkError`` and
``JmapProtocolError`` both inherit from ``JmapError`` (``include/aspose_jmap/models/
CommonTypes.hpp``) and each copies down ``JmapError``'s own constructor, correctly rooted to
``aspose_jmap::JmapError``. ``JmapError`` itself inherits from ``std::runtime_error``, which is
not a project type present in this fixture's own ``types`` list, so nothing is copied down
from it - an external/stdlib base correctly contributes no ``inherited_from`` tags of its own.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

FIXTURE = Path(__file__).parents[1] / "fixtures" / "jmap_cpp" / "api_surface.json"
MANIFEST = Path(__file__).parents[2] / "config" / "products" / "jmap" / "cpp.yaml"

_COMMIT_SHA = re.compile(r"^[0-9a-f]{40}$")


def _load_fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_the_fixture_parses_and_has_the_expected_shape() -> None:
    data = _load_fixture()
    assert isinstance(data, dict)
    assert isinstance(data["types"], list)
    assert data["language"] == "cpp"


def test_the_fixture_records_the_exact_source_commit_and_repository() -> None:
    data = _load_fixture()
    assert _COMMIT_SHA.match(data["source_commit"]), data["source_commit"]
    # Recorded from the real live clone that produced this fixture - re-verify by hand with
    # `git ls-remote https://github.com/aspose-email-foss/Aspose.JMAP-FOSS-for-Cpp` if this
    # ever needs re-pinning; do not change it to make a test pass.
    assert data["source_commit"] == "559c962081323468039dc75cf38676499f32b20e"
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    assert data["source_repository"] == manifest["repository"]


def test_the_fixture_is_non_empty() -> None:
    data = _load_fixture()
    assert len(data["types"]) > 0
    assert data["reduced_type_count"] == len(data["types"])
    # The real repository has only 39 public types - well under the CLI's default
    # --max-types 300 cap, so this fixture is the full, untruncated surface.
    assert data["type_count"] == 39
    assert data["truncated"] is False


def test_the_fixture_contains_real_cpp_type_names() -> None:
    data = _load_fixture()
    names = {entry["name"] for entry in data["types"]}
    # Real Aspose.JMAP-FOSS-for-Cpp types, not placeholders - would not survive an empty or
    # synthetic fixture.
    assert {"Account", "Comparator", "CoreCapability", "EmailAddress"} <= names
    # Header-only: every real entry lives in a .hpp file, no .cpp translation unit.
    assert all(entry["file"].endswith(".hpp") for entry in data["types"])


def test_every_entry_is_a_real_cpp_surface_kind() -> None:
    data = _load_fixture()
    kinds = {entry["kind"] for entry in data["types"]}
    # Observed directly from the live tree-sitter C++ grammar's own node-type vocabulary
    # for this repository, not guessed or invented.
    assert kinds == {"class_specifier", "struct_specifier"}


def test_real_inheritance_relationships_are_present() -> None:
    data = _load_fixture()
    by_name = {entry["name"]: entry for entry in data["types"]}

    # Observed directly in the live run: JmapClient really inherits from both mixins, each of
    # which really inherits from JmapClientCore - a genuine, non-trivial base to copy from,
    # unlike this wave's genuinely-flat siblings (jmap/go, cells/rust).
    assert by_name["JmapClient"]["bases"] == ["MailClientMixin", "SubmissionClientMixin"]
    assert by_name["MailClientMixin"]["bases"] == ["JmapClientCore"]
    assert by_name["SubmissionClientMixin"]["bases"] == ["JmapClientCore"]

    # A simpler, one-level relationship: both error subclasses inherit from JmapError, which
    # itself inherits from the external/stdlib std::runtime_error (not a project type present
    # in this fixture's own types list).
    assert by_name["JmapNetworkError"]["bases"] == ["JmapError"]
    assert by_name["JmapProtocolError"]["bases"] == ["JmapError"]
    assert by_name["JmapError"]["bases"] == ["std::runtime_error"]


def test_a_real_multilevel_inherited_from_chain_is_correctly_rooted() -> None:
    data = _load_fixture()
    by_name = {entry["name"]: entry for entry in data["types"]}

    # Real two-level chain observed directly in the live run: JmapClient -> MailClientMixin ->
    # JmapClientCore (and, independently, JmapClient -> SubmissionClientMixin ->
    # JmapClientCore). TC-261 (C3) added "inherited_from" provenance tagging to
    # _flatten_inheritance(); the previously-committed fixture (TC-232, before TC-261 landed)
    # carried these same real bases lists but zero "inherited_from" tags anywhere. TC-308
    # re-ran the identical extraction now that TC-261 is on main.
    mail_mixin_methods = {m["name"]: m for m in by_name["MailClientMixin"]["methods"]}
    client_methods = {m["name"]: m for m in by_name["JmapClient"]["methods"]}

    # A method MailClientMixin itself declares, copied one level into JmapClient, roots to
    # MailClientMixin - the real, direct declaring ancestor.
    assert "inherited_from" not in mail_mixin_methods["listMailboxes"]
    assert client_methods["listMailboxes"]["inherited_from"] == "aspose_jmap::MailClientMixin"

    # A method that originates in JmapClientCore and is copied TRANSITIVELY into JmapClient
    # (through MailClientMixin, which never declares it itself) roots to JmapClientCore - the
    # true, original declaring ancestor - not to MailClientMixin, the intermediate parent it
    # was copied through. This is the exact multi-level rooting behavior TC-261's own fix
    # targets.
    for member in ("connect", "sendRequest", "echo", "uploadBlob", "downloadBlob"):
        assert client_methods[member]["inherited_from"] == "aspose_jmap::JmapClientCore"

    # MailClientMixin's OWN copy of these same JmapClientCore-declared methods (one level up
    # the chain) already roots to JmapClientCore too - confirming the parent's own
    # already-resolved inherited_from survives being copied again into the grandchild rather
    # than being overwritten with the intermediate parent's identity.
    for member in ("connect", "sendRequest", "echo", "uploadBlob", "downloadBlob"):
        assert mail_mixin_methods[member]["inherited_from"] == "aspose_jmap::JmapClientCore"

    # The same shape holds down the SubmissionClientMixin branch of the chain.
    submission_mixin_methods = {m["name"]: m for m in by_name["SubmissionClientMixin"]["methods"]}
    assert "inherited_from" not in submission_mixin_methods["send"]
    assert client_methods["send"]["inherited_from"] == "aspose_jmap::SubmissionClientMixin"

    # A genuinely locally-declared method never gains an inherited_from key at all.
    assert "inherited_from" not in client_methods["JmapClient"]


def test_a_one_level_inherited_from_relationship_is_correctly_rooted() -> None:
    data = _load_fixture()
    by_name = {entry["name"]: entry for entry in data["types"]}

    jmap_error_methods = {m["name"]: m for m in by_name["JmapError"]["methods"]}
    network_error_methods = {m["name"]: m for m in by_name["JmapNetworkError"]["methods"]}
    protocol_error_methods = {m["name"]: m for m in by_name["JmapProtocolError"]["methods"]}

    # JmapError's own constructor is genuinely locally declared.
    assert "inherited_from" not in jmap_error_methods["JmapError"]

    # Both subclasses copy that same constructor down, correctly rooted to JmapError - the
    # real, direct (and only) declaring ancestor present in this fixture's own types list.
    assert network_error_methods["JmapError"]["inherited_from"] == "aspose_jmap::JmapError"
    assert protocol_error_methods["JmapError"]["inherited_from"] == "aspose_jmap::JmapError"

    # std::runtime_error (JmapError's own base) is an external/stdlib type, not present in
    # this fixture's own types list, so nothing is copied down from it - JmapError carries no
    # inherited_from tags of its own.
    for member in jmap_error_methods.values():
        assert "inherited_from" not in member
