"""Offline tests against the committed pdf/net fixture - no network, no live clone, no engine.

``gatectl`` verifies this card with the network proxied to a dead port (TC-011 sets
``network: false``), so nothing here may reach out; everything is read from the fixture
``run_extraction.py`` already produced and committed at
``tests/fixtures/pdf_net/api_surface.json``.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

FIXTURE = Path(__file__).parents[1] / "fixtures" / "pdf_net" / "api_surface.json"
MANIFEST = Path(__file__).parents[2] / "config" / "products" / "pdf" / "net.yaml"

_COMMIT_SHA = re.compile(r"^[0-9a-f]{40}$")


def _load_fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_the_fixture_parses_and_has_the_expected_shape() -> None:
    data = _load_fixture()
    assert isinstance(data, dict)
    assert isinstance(data["types"], list)


def test_the_fixture_records_the_exact_source_commit_and_repository() -> None:
    data = _load_fixture()
    assert _COMMIT_SHA.match(data["source_commit"]), data["source_commit"]
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    assert data["source_repository"] == manifest["repository"]


def test_the_fixture_is_non_empty() -> None:
    data = _load_fixture()
    assert len(data["types"]) > 0
    assert data["reduced_type_count"] == len(data["types"])
    assert data["type_count"] >= data["reduced_type_count"]


def test_the_fixture_contains_real_dotnet_type_names() -> None:
    data = _load_fixture()
    names = {entry["name"] for entry in data["types"]}
    # Real Aspose.PDF types, not placeholders - would not survive an empty or synthetic fixture.
    assert {"Page", "Document", "ActionCollection"} <= names
    assert all(entry.get("class_import", "").startswith("Aspose.Pdf") for entry in data["types"])
    assert all(entry["file"].endswith(".cs") for entry in data["types"])


def test_the_fixture_keeps_page_after_the_centrality_ranked_selection_fix() -> None:
    """TC-252 replaced reduce_fixture's alphabetical truncation with a centrality-ranked one;
    before that fix this fixture's reduced 300 never included "Page" even though 899-971 real
    types existed upstream. This is the concrete proof the fix recovers it for this pilot: a
    type named exactly "Page" (not e.g. "ExamplePage") must be among the 300 kept types, with
    its own real qualified name and source file."""
    data = _load_fixture()
    page_entries = [entry for entry in data["types"] if entry["name"] == "Page"]
    assert page_entries, "Page" + " must be present among the kept types"
    page = page_entries[0]
    assert page["class_import"] == "Aspose.Pdf.Page"
    assert page["kind"] == "class_declaration"
    assert page["file"].endswith(".cs")


def test_every_entry_is_a_real_csharp_declaration_kind() -> None:
    data = _load_fixture()
    kinds = {entry["kind"] for entry in data["types"]}
    assert kinds <= {
        "class_declaration",
        "struct_declaration",
        "interface_declaration",
        "enum_declaration",
    }
    assert kinds


def test_popup_annotation_carries_correctly_rooted_multi_level_inherited_from() -> None:
    """TC-284 (G2): this fixture was regenerated by TC-263 BEFORE TC-261 (the C3 fix that
    makes ``_flatten_inheritance`` tag every copied member with an explicit ``inherited_from``)
    landed on main, so the committed fixture carried zero ``inherited_from`` tags despite real
    inheritance - including this exact pilot's own real PopupAnnotation -> Annotation ->
    BaseParagraph chain, which is TC-261's own live-verified worked example. Now that both
    TC-252 and TC-261 are on main and the fixture has been re-extracted for real, this proves
    the chain is tagged, and tagged correctly: a member genuinely declared by BaseParagraph and
    flattened two levels down onto PopupAnnotation must be rooted to BaseParagraph itself - the
    real original declaring ancestor - never to Annotation, the intermediate parent it was
    copied through."""
    data = _load_fixture()
    types = {entry["name"]: entry for entry in data["types"]}
    assert {"PopupAnnotation", "Annotation", "BaseParagraph"} <= set(types)

    popup = types["PopupAnnotation"]
    annotation = types["Annotation"]
    base_paragraph = types["BaseParagraph"]
    assert popup["bases"] == ["Annotation"]
    assert annotation["bases"] == ["BaseParagraph"]

    # BaseParagraph genuinely declares "Clone" itself - no inherited_from on its own entry.
    base_methods = {m["name"]: m for m in base_paragraph.get("methods", [])}
    assert "Clone" in base_methods
    assert "inherited_from" not in base_methods["Clone"]

    # Flattened one level onto Annotation, "Clone" is rooted to BaseParagraph, its real
    # original declarer - not left untagged.
    annotation_methods = {m["name"]: m for m in annotation.get("methods", [])}
    assert annotation_methods["Clone"]["inherited_from"] == "Aspose.Pdf.BaseParagraph"

    # Flattened a SECOND level onto PopupAnnotation (through Annotation), "Clone" still
    # roots to BaseParagraph itself, never to Annotation, the intermediate parent it was
    # actually copied through on this hop - this is the exact multi-level provenance C3/TC-261
    # fixed and this pilot's own regeneration had been missing.
    popup_methods = {m["name"]: m for m in popup.get("methods", [])}
    assert popup_methods["Clone"]["inherited_from"] == "Aspose.Pdf.BaseParagraph"

    # Same chain, a property this time: flattened two levels, still rooted to BaseParagraph.
    popup_props = {p["name"]: p for p in popup.get("properties", [])}
    assert popup_props["Margin"]["inherited_from"] == "Aspose.Pdf.BaseParagraph"

    # "Action" is genuinely declared by Annotation itself (not inherited from BaseParagraph)
    # and is not overridden by PopupAnnotation, so when flattened onto PopupAnnotation it must
    # root to Annotation - provenance distinguishes the two ancestors rather than collapsing
    # everything in the chain onto one root.
    assert "Action" in {p["name"] for p in annotation.get("properties", [])}
    assert "inherited_from" not in {p["name"]: p for p in annotation.get("properties", [])}["Action"]
    popup_props_all = {p["name"]: p for p in popup.get("properties", [])}
    assert popup_props_all["Action"]["inherited_from"] == "Aspose.Pdf.Annotations.Annotation"


def test_fixture_wide_inherited_from_tagging_is_present() -> None:
    """A coarse, whole-fixture check that TC-261's provenance tagging actually ran during this
    pilot's own regeneration - not just on the one hand-picked PopupAnnotation chain above.
    Before TC-261 landed, this exact fixture (regenerated by TC-263 earlier the same day) had
    real flattened inheritance but exactly zero "inherited_from" tags anywhere."""
    data = _load_fixture()
    tagged = sum(
        1
        for entry in data["types"]
        for member in entry.get("methods", []) + entry.get("properties", [])
        if "inherited_from" in member
    )
    assert tagged > 0
