"""Offline tests against the committed 3d/python fixture - no network, no live clone.

``gatectl`` verifies this card with the network proxied to a dead port (this card's own
``network: false``), so nothing here may reach out; everything is read from the fixture
``run_extraction.py`` already produced and committed at
``tests/fixtures/3d_python/api_surface.json``.

Like pdf/python and slides/python, this fixture was produced by the independent pure-``ast``
reader (``foss_mcp.extraction.tree_sitter_engine.python_surface``, adapted in
``run_extraction._python_types_from_surface``): its ``language`` field reads literally
``"python"`` and there is no tree-sitter grammar name here at all.

Regenerated by TC-266 against the exact same pinned commit the prior, pre-fix fixture
recorded (``65b1f577c0f16d0d9112bb6c1153d3024543ac02``) - this repository had not advanced -
now that both of this fixture's dependencies are genuinely integrated on main: TC-252's
``reduce_fixture()`` selects the kept 300 by CENTRALITY score (how many other types reference
a type's bare name), tie-broken by ``class_import``, not alphabetically; and TC-265 makes that
centrality score non-degenerate for a Python-sourced fixture specifically, by populating real
``bases``/``return_type``/``param_types`` from the AST (0 entries had a non-empty ``bases`` and
0 methods had a ``return_type`` in the OLD, pre-TC-265 fixture; this regenerated one has 139
and 469 respectively). The real repository's full public surface is 697 types - over the CLI's
default ``--max-types 300`` cap - so this fixture is still a reduced, deterministic 300-entry
sample: ``type_count`` (697) is greater than ``reduced_type_count`` (300). Observed directly
from the live run, not assumed from a sibling platform's fixture: the reduced sample's own kind
vocabulary is only ``{"class", "enum"}`` - no top-level ``"function"`` entry survives the
centrality-ranked cut to 300, unlike pdf/python's reduced sample.

Independently computed directly against this same live run (re-running
``extract_pinned_repository`` + ``run_extraction._centrality_scores`` over the full,
untruncated 697-type list - see this card's own report): the single highest-centrality type in
the entire real surface is ``A3DObject`` (``aspose.threed.A3DObject``, score 35 - referenced by
35 other types' bases/return_type/param_types), with a second, same-named entry for the
submodule-qualified original (``aspose.threed.A3DObject.A3DObject``) tied at the same score.
Both are confirmed present among the 300 kept types below and are literally the fixture's own
first two entries.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

FIXTURE = Path(__file__).parents[1] / "fixtures" / "3d_python" / "api_surface.json"
MANIFEST = Path(__file__).parents[2] / "config" / "products" / "3d" / "python.yaml"

_COMMIT_SHA = re.compile(r"^[0-9a-f]{40}$")


def _load_fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_the_fixture_parses_and_has_the_expected_shape() -> None:
    data = _load_fixture()
    assert isinstance(data, dict)
    assert isinstance(data["types"], list)
    assert data["language"] == "python"


def test_the_fixture_records_the_exact_source_commit_and_repository() -> None:
    data = _load_fixture()
    assert _COMMIT_SHA.match(data["source_commit"]), data["source_commit"]
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    assert data["source_repository"] == manifest["repository"]


def test_the_fixture_is_non_empty() -> None:
    data = _load_fixture()
    assert len(data["types"]) > 0
    assert data["reduced_type_count"] == len(data["types"])
    assert data["type_count"] >= data["reduced_type_count"]


def test_the_fixture_contains_real_python_type_names() -> None:
    data = _load_fixture()
    names = {entry["name"] for entry in data["types"]}
    # Real Aspose.3D-FOSS-for-Python classes/enums, not placeholders - would not survive an
    # empty or synthetic fixture.
    assert {"A3DObject", "AnimationChannel", "AssetInfo", "Axis"} <= names
    assert all(entry["class_import"].startswith("aspose") for entry in data["types"])
    assert all(entry["file"].endswith(".py") for entry in data["types"])


def test_every_entry_is_a_real_python_surface_kind() -> None:
    data = _load_fixture()
    kinds = {entry["kind"] for entry in data["types"]}
    # Observed directly from the live pure-ast reader's output for this repository, not
    # guessed: the reduced 300-entry sample only contains "class" and "enum" entries, a
    # subset of the reader's full {"class", "enum", "function"} vocabulary (see
    # pdf/python's own test for a sample that does retain top-level functions).
    assert kinds
    assert kinds <= {"class", "enum", "function"}


def test_the_fixture_keeps_a3dobject_after_the_centrality_ranked_selection_fix() -> None:
    """TC-252 replaced ``reduce_fixture``'s alphabetical truncation with a centrality-ranked
    one, and TC-265 made that score non-degenerate for a Python-sourced fixture by populating
    real ``bases``/``return_type``/``param_types``. Independently re-measured directly against
    this fixture's own live run (re-running ``extract_pinned_repository`` plus
    ``run_extraction._centrality_scores`` over the full, untruncated 697-type list - not
    guessed, not carried over from another pilot): ``A3DObject`` is the single
    highest-centrality type in the entire real surface, referenced by 35 other types' bases/
    return_type/param_types - the highest score of any type measured. This is the concrete
    proof the fix recovers it for this pilot: both the public re-export
    (``aspose.threed.A3DObject``) and the submodule-qualified original
    (``aspose.threed.A3DObject.A3DObject``) must be among the 300 kept types."""
    data = _load_fixture()
    by_class_import = {entry["class_import"]: entry for entry in data["types"]}
    for class_import in ("aspose.threed.A3DObject", "aspose.threed.A3DObject.A3DObject"):
        assert class_import in by_class_import, class_import + " must be present among the kept types"
        entry = by_class_import[class_import]
        assert entry["name"] == "A3DObject"
        assert entry["kind"] == "class"
        assert entry["bases"] == ["INamedObject"]
        assert entry["file"].endswith(".py")
