"""Offline tests against the committed barcode/python fixture - no network, no live clone.

``gatectl`` verifies this card with the network proxied to a dead port (TC-152 sets
``network: false``), so nothing here may reach out; everything is read from the fixture
``run_extraction.py`` already produced and committed at
``tests/fixtures/barcode_python/api_surface.json``.

Like slides/python (and unlike pdf/net's tree-sitter/C# reader), this fixture was
produced by the independent pure-``ast`` reader
(``foss_mcp.extraction.tree_sitter_engine.python_surface``, adapted in
``run_extraction._python_types_from_surface``): its ``language`` field reads literally
``"python"`` and there is no tree-sitter grammar name here at all. Unlike slides/python,
this repository's reduced 70-entry surface does survive top-level functions: the
observed ``kind`` vocabulary is ``{"class", "enum", "function"}``.

TC-318's own regeneration history: this fixture was originally generated by TC-152 (the
original onboarding wave), which predates TC-252 (centrality-ranked ``reduce_fixture``),
TC-261 (``inherited_from`` provenance tagging), and the underscore-origin re-export
recovery chain TC-274/TC-281/TC-293/TC-294 built on top of ``python_surface.py``'s
``_origin_definition``/``_reexported_methods``. Every one of the original fixture's 70
entries carried ``bases: []`` and ``properties: []`` for that reason alone, not because
the real upstream repository lacks inheritance.

A real live re-run (same pinned commit, ``06eca5c01e13ed6d59a640f1cf330c1c5a57d151`` -
unchanged from TC-152's own pin, so this card hit no commit-pin-divergence) now produces
real, non-empty ``bases`` on 44 of the 70 entries, hand-confirmed against the real
upstream source at that commit (fetched directly via
``raw.githubusercontent.com/aspose-barcode-foss/Aspose.BarCode-FOSS-for-Python/<sha>/...``):

- ``BarcodeError(Exception)`` in ``src/aspose_barcode_foss/_internal/exceptions.py``
  (public re-export path: ``src/aspose_barcode_foss/exceptions.py`` and the package's own
  ``__init__.py``), with six real subclasses - ``SymbologyNotFoundError``,
  ``EncodingError``, ``RenderingError``, ``InvalidInputError``, ``UnsupportedFeatureError``,
  ``UnsupportedCapabilityError`` - every one a pure marker exception with no body beyond a
  docstring. This is exactly the underscore-origin re-export pattern TC-274/TC-281/TC-293/
  TC-294 were built to handle.
- ``Renderer(ABC)`` in ``src/aspose_barcode_foss/_internal/renderers/base.py`` (an
  ``abstractmethod render(...)``), with three real subclasses - ``PdfRenderer``,
  ``PngRenderer``, ``SvgRenderer`` - each in its own underscore-origin module.
- ``EncodeOptions`` (a frozen ``dataclass`` in
  ``src/aspose_barcode_foss/_internal/models/options.py``), with seven real subclasses -
  ``Code128Options``, ``Code39Options``, ``Ean13Options``, ``Ean8Options``, ``QrOptions``,
  ``UpcaOptions``, ``UpceOptions``.
- Four real ``Enum`` subclasses: ``Code128EncodeMode``, ``Code39EncodeMode``,
  ``QrEncodeMode``, ``QrErrorCorrectionLevel``.

Despite this real, non-trivial inheritance, this live re-run genuinely produces zero
``inherited_from`` tags anywhere in the fixture - hand-verified against the real upstream
source, not assumed, mirroring the TC-301/TC-303/TC-312 precedent:

- Every ``BarcodeError`` subclass is a pure marker class with no methods of its own and
  inherits nothing but ``Exception``'s own built-in members, which this package never
  scans (``Exception`` is not part of the inspected source tree).
- ``PdfRenderer``/``PngRenderer``/``SvgRenderer`` each *override* ``Renderer``'s single
  abstract ``render`` method with their own real implementation rather than inheriting
  it - confirmed directly in each module's own source - so ``_flatten_inheritance`` has
  nothing left uncopied to tag.
- ``EncodeOptions`` and its seven subclasses are frozen dataclasses whose fields are
  ``ast.AnnAssign`` statements, not ``ast.FunctionDef``/``ast.AsyncFunctionDef`` nodes;
  ``python_surface.py``'s ``_methods()`` only ever walks function definitions, so no
  dataclass field is ever recorded as a ``property`` at all (every entry's own
  ``properties`` list is empty, fixture-wide) - there is nothing for ``inherited_from`` to
  attach to.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

FIXTURE = Path(__file__).parents[1] / "fixtures" / "barcode_python" / "api_surface.json"
MANIFEST = Path(__file__).parents[2] / "config" / "products" / "barcode" / "python.yaml"

_COMMIT_SHA = re.compile(r"^[0-9a-f]{40}$")


def _load_fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_the_fixture_parses_and_has_the_expected_shape() -> None:
    data = _load_fixture()
    assert isinstance(data, dict)
    assert isinstance(data["types"], list)
    assert data["language"] == "python"


def test_the_fixture_records_the_exact_source_commit_and_repository() -> None:
    data = _load_fixture()
    assert _COMMIT_SHA.match(data["source_commit"]), data["source_commit"]
    # Unchanged from TC-152's own pin - this card's live re-run hit no commit-pin-
    # divergence (unlike several sibling pilots this session); re-verify by hand with
    # `git ls-remote https://github.com/aspose-barcode-foss/Aspose.BarCode-FOSS-for-Python`
    # if this ever needs re-pinning, and do not change it to make a test pass.
    assert data["source_commit"] == "06eca5c01e13ed6d59a640f1cf330c1c5a57d151"
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    assert data["source_repository"] == manifest["repository"]


def test_the_fixture_is_non_empty_and_records_real_truncation() -> None:
    data = _load_fixture()
    assert len(data["types"]) > 0
    assert data["reduced_type_count"] == len(data["types"])
    # The real repository's complete reduced public surface is 70 types, same count as
    # TC-152's own original pin - this re-run changed the content (bases/docstrings), not
    # the surface's size or truncation state.
    assert data["type_count"] == 70
    assert data["reduced_type_count"] == 70
    assert data["truncated"] is False


def test_the_fixture_contains_real_python_type_names() -> None:
    data = _load_fixture()
    names = {entry["name"] for entry in data["types"]}
    # Real Aspose.BarCode-FOSS-for-Python classes/enums/functions, not placeholders -
    # would not survive an empty or synthetic fixture.
    assert {"Barcode", "BarcodeError", "Code128EncodeMode"} <= names
    assert all(entry["class_import"].startswith("aspose_barcode_foss") for entry in data["types"])
    assert all(entry["file"].endswith(".py") for entry in data["types"])


def test_every_entry_is_a_real_python_surface_kind() -> None:
    data = _load_fixture()
    kinds = {entry["kind"] for entry in data["types"]}
    # Observed directly from the live pure-ast reader's output for this repository - not
    # a tree-sitter grammar's node-type vocabulary, and not guessed. Unlike slides/python,
    # this reduced surface does retain top-level module functions (e.g. "generate",
    # "qr") alongside classes and enums.
    assert kinds == {"class", "enum", "function"}


def test_a_real_top_level_function_is_present() -> None:
    data = _load_fixture()
    functions = {entry["name"] for entry in data["types"] if entry["kind"] == "function"}
    # Real top-level encoder functions from src/aspose_barcode_foss/api.py, observed
    # directly in this card's own run - not guessed.
    assert {"generate", "qr", "code128"} <= functions


def test_real_inheritance_now_populates_bases_on_three_distinct_hierarchies() -> None:
    """TC-318's own live re-run, under the full TC-252/TC-261/TC-274/TC-281/TC-293/TC-294
    pipeline: real ``bases`` now populate on exactly the underscore-origin re-export
    pattern this fixture predates, hand-confirmed against the real pinned upstream source
    (``06eca5c01e13ed6d59a640f1cf330c1c5a57d151``) rather than guessed.
    """
    data = _load_fixture()
    by_import = {entry["class_import"]: entry for entry in data["types"] if entry.get("class_import")}

    # Exception hierarchy: `class BarcodeError(Exception)` and six real subclasses, defined
    # in the underscore-origin `_internal/exceptions.py` and re-exported both from the
    # package's own `exceptions.py` and its top-level `__init__.py`.
    assert by_import["aspose_barcode_foss.BarcodeError"]["bases"] == ["Exception"]
    assert by_import["aspose_barcode_foss.exceptions.BarcodeError"]["bases"] == ["Exception"]
    exception_subclasses = {
        "SymbologyNotFoundError",
        "EncodingError",
        "RenderingError",
        "InvalidInputError",
        "UnsupportedFeatureError",
        "UnsupportedCapabilityError",
    }
    for name in exception_subclasses:
        assert by_import[f"aspose_barcode_foss.{name}"]["bases"] == ["BarcodeError"]
        assert by_import[f"aspose_barcode_foss.exceptions.{name}"]["bases"] == ["BarcodeError"]

    # Renderer hierarchy: `class Renderer(ABC)` with an abstractmethod `render`, and three
    # real subclasses - each defined in its own underscore-origin module
    # (`_internal/renderers/{base,pdf,png,svg}.py`) and re-exported from both
    # `renderers.py` and the top-level `__init__.py`.
    assert by_import["aspose_barcode_foss.Renderer"]["bases"] == ["ABC"]
    assert by_import["aspose_barcode_foss.renderers.Renderer"]["bases"] == ["ABC"]
    for name in ("PdfRenderer", "PngRenderer", "SvgRenderer"):
        assert by_import[f"aspose_barcode_foss.{name}"]["bases"] == ["Renderer"]
        assert by_import[f"aspose_barcode_foss.renderers.{name}"]["bases"] == ["Renderer"]

    # EncodeOptions hierarchy: a frozen dataclass base with seven real subclasses, defined
    # in `_internal/models/options.py` and re-exported from both `options.py` and the
    # top-level `__init__.py`.
    for name in (
        "Code128Options",
        "Code39Options",
        "Ean13Options",
        "Ean8Options",
        "QrOptions",
        "UpcaOptions",
        "UpceOptions",
    ):
        assert by_import[f"aspose_barcode_foss.{name}"]["bases"] == ["EncodeOptions"]
        assert by_import[f"aspose_barcode_foss.options.{name}"]["bases"] == ["EncodeOptions"]

    # Four real Enum subclasses.
    for name in ("Code128EncodeMode", "Code39EncodeMode", "QrEncodeMode", "QrErrorCorrectionLevel"):
        assert by_import[f"aspose_barcode_foss.{name}"]["bases"] == ["Enum"]
        assert by_import[f"aspose_barcode_foss.options.{name}"]["bases"] == ["Enum"]

    # Exactly 44 of the 70 entries carry a real non-empty `bases` list - hand-counted
    # above (14 exception-hierarchy + 8 Renderer-hierarchy + 14 EncodeOptions-hierarchy +
    # 8 Enum, each doubled by the public/underscore-origin re-export pair).
    non_empty_bases = [entry for entry in data["types"] if entry.get("bases")]
    assert len(non_empty_bases) == 44


def test_inherited_from_is_genuinely_absent_despite_real_inheritance() -> None:
    """Zero ``inherited_from`` tags anywhere in this fixture is a hand-verified genuine
    absence, not an unexercised pipeline - mirroring the TC-301/TC-303/TC-312 precedent.

    Confirmed directly against the real pinned upstream source
    (``06eca5c01e13ed6d59a640f1cf330c1c5a57d151``): every ``BarcodeError`` subclass is a
    pure marker exception with no method body beyond a docstring, so it inherits nothing
    from ``BarcodeError`` that this package's own extractor ever scans; ``PdfRenderer``,
    ``PngRenderer``, and ``SvgRenderer`` each *override* ``Renderer``'s single abstract
    ``render`` method with their own real implementation (confirmed in each module's own
    source) rather than inheriting it, so ``_flatten_inheritance`` has nothing left
    uncopied to tag; and ``EncodeOptions``/its seven subclasses are frozen dataclasses
    whose fields are ``ast.AnnAssign`` statements that ``python_surface.py``'s own
    ``_methods()`` never records as a ``property`` at all (confirmed below: every entry's
    ``properties`` list is empty, fixture-wide), leaving nothing for ``inherited_from`` to
    attach to.
    """
    data = _load_fixture()

    for entry in data["types"]:
        assert entry["properties"] == [], entry["class_import"]
        for method in entry.get("methods", []):
            assert "inherited_from" not in method, (entry["class_import"], method["name"])
        for prop in entry.get("properties", []):
            assert "inherited_from" not in prop, (entry["class_import"], prop["name"])

    # `Renderer`'s own abstract `render` and each subclass's own overriding `render` are
    # real, distinct method entries (not copies) - confirmed by their shared signature
    # shape but each one's own, non-copied presence.
    by_import = {entry["class_import"]: entry for entry in data["types"] if entry.get("class_import")}
    for name in ("Renderer", "PdfRenderer", "PngRenderer", "SvgRenderer"):
        entry = by_import[f"aspose_barcode_foss.{name}"]
        method_names = [m["name"] for m in entry["methods"]]
        assert method_names == ["render"]
        render = entry["methods"][0]
        assert render["return_type"] == "RenderedArtifact"
        assert [p["name"] for p in render["params"]] == ["symbol", "layout", "options"]
