"""Offline tests against the committed 3d/python fixture - no network, no live clone.

``gatectl`` verifies this card with the network proxied to a dead port (this card's own
``network: false``), so nothing here may reach out; everything is read from the fixture
``run_extraction.py`` already produced and committed at
``tests/fixtures/3d_python/api_surface.json``.

Like pdf/python and slides/python, this fixture was produced by the independent pure-``ast``
reader (``foss_mcp.extraction.tree_sitter_engine.python_surface``, adapted in
``run_extraction._python_types_from_surface``): its ``language`` field reads literally
``"python"`` and there is no tree-sitter grammar name here at all.

Regenerated by TC-266 against the exact same pinned commit the prior, pre-fix fixture
recorded (``65b1f577c0f16d0d9112bb6c1153d3024543ac02``) - this repository had not advanced -
now that both of this fixture's dependencies are genuinely integrated on main: TC-252's
``reduce_fixture()`` selects the kept 300 by CENTRALITY score (how many other types reference
a type's bare name), tie-broken by ``class_import``, not alphabetically; and TC-265 makes that
centrality score non-degenerate for a Python-sourced fixture specifically, by populating real
``bases``/``return_type``/``param_types`` from the AST (0 entries had a non-empty ``bases`` and
0 methods had a ``return_type`` in the OLD, pre-TC-265 fixture; this regenerated one has 139
and 469 respectively). The real repository's full public surface is 697 types - over the CLI's
default ``--max-types 300`` cap - so this fixture is still a reduced, deterministic 300-entry
sample: ``type_count`` (697) is greater than ``reduced_type_count`` (300). Observed directly
from the live run, not assumed from a sibling platform's fixture: the reduced sample's own kind
vocabulary is only ``{"class", "enum"}`` - no top-level ``"function"`` entry survives the
centrality-ranked cut to 300, unlike pdf/python's reduced sample.

Independently computed directly against this same live run (re-running
``extract_pinned_repository`` + ``run_extraction._centrality_scores`` over the full,
untruncated 697-type list - see this card's own report): the single highest-centrality type in
the entire real surface is ``A3DObject`` (``aspose.threed.A3DObject``, score 35 - referenced by
35 other types' bases/return_type/param_types), with a second, same-named entry for the
submodule-qualified original (``aspose.threed.A3DObject.A3DObject``) tied at the same score.
Both are confirmed present among the 300 kept types below and are literally the fixture's own
first two entries.

TC-288/TC-293 (2026-10-09): this fixture was regenerated a second time, against the exact same
pinned commit again, once TC-293 landed. TC-281 had already made ``_flatten_inheritance()``
execute for Python (it did not before), but a deeper, pre-existing defect in that function's
own short-name index meant it still copied ZERO members anywhere in this entire 697-type
pilot - confirmed live, three independent ways, by TC-288 before TC-293's fix existed: every
one of this pilot's real classes following the common "class defined in its own submodule,
re-exported at the package level" layout (e.g. ``A3DObject`` itself) produces both an empty
re-export shell (``aspose.threed.A3DObject``) and the real, member-bearing definition
(``aspose.threed.A3DObject.A3DObject``) sharing one bare name, and every subclass's ``bases``
entry is written as that bare name (e.g. ``AssetInfo``'s ``bases == ["A3DObject"]``) - which
used to resolve straight to the empty shell. TC-293 fixed the short-name index itself to prefer
a structured-data-bearing candidate over an empty shell on collision. This second regeneration
is the concrete, live proof that the fix reaches this pilot: 0 ``inherited_from`` tags before
TC-293, 358 after, on this exact same pinned commit. The Node/SceneObject/A3DObject chain
below is a REAL multi-level case confirmed directly against this fixture (not invented,
mirroring TC-261's own pdf/cpp PopupAnnotation/Annotation/BaseParagraph proof): ``Node``'s
``bases`` names only its direct parent ``SceneObject``, but ``find_property`` (and 5 further
members) are genuinely declared by the grandparent ``A3DObject``, copied into ``SceneObject``
first and then into ``Node``, and correctly rooted to ``A3DObject`` throughout - never to the
intermediate ``SceneObject``.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

FIXTURE = Path(__file__).parents[1] / "fixtures" / "3d_python" / "api_surface.json"
MANIFEST = Path(__file__).parents[2] / "config" / "products" / "3d" / "python.yaml"

_COMMIT_SHA = re.compile(r"^[0-9a-f]{40}$")


def _load_fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_the_fixture_parses_and_has_the_expected_shape() -> None:
    data = _load_fixture()
    assert isinstance(data, dict)
    assert isinstance(data["types"], list)
    assert data["language"] == "python"


def test_the_fixture_records_the_exact_source_commit_and_repository() -> None:
    data = _load_fixture()
    assert _COMMIT_SHA.match(data["source_commit"]), data["source_commit"]
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    assert data["source_repository"] == manifest["repository"]


def test_the_fixture_is_non_empty() -> None:
    data = _load_fixture()
    assert len(data["types"]) > 0
    assert data["reduced_type_count"] == len(data["types"])
    assert data["type_count"] >= data["reduced_type_count"]


def test_the_fixture_contains_real_python_type_names() -> None:
    data = _load_fixture()
    names = {entry["name"] for entry in data["types"]}
    # Real Aspose.3D-FOSS-for-Python classes/enums, not placeholders - would not survive an
    # empty or synthetic fixture.
    assert {"A3DObject", "AnimationChannel", "AssetInfo", "Axis"} <= names
    assert all(entry["class_import"].startswith("aspose") for entry in data["types"])
    assert all(entry["file"].endswith(".py") for entry in data["types"])


def test_every_entry_is_a_real_python_surface_kind() -> None:
    data = _load_fixture()
    kinds = {entry["kind"] for entry in data["types"]}
    # Observed directly from the live pure-ast reader's output for this repository, not
    # guessed: the reduced 300-entry sample only contains "class" and "enum" entries, a
    # subset of the reader's full {"class", "enum", "function"} vocabulary (see
    # pdf/python's own test for a sample that does retain top-level functions).
    assert kinds
    assert kinds <= {"class", "enum", "function"}


def test_the_fixture_keeps_a3dobject_after_the_centrality_ranked_selection_fix() -> None:
    """TC-252 replaced ``reduce_fixture``'s alphabetical truncation with a centrality-ranked
    one, and TC-265 made that score non-degenerate for a Python-sourced fixture by populating
    real ``bases``/``return_type``/``param_types``. Independently re-measured directly against
    this fixture's own live run (re-running ``extract_pinned_repository`` plus
    ``run_extraction._centrality_scores`` over the full, untruncated 697-type list - not
    guessed, not carried over from another pilot): ``A3DObject`` is the single
    highest-centrality type in the entire real surface, referenced by 35 other types' bases/
    return_type/param_types - the highest score of any type measured. This is the concrete
    proof the fix recovers it for this pilot: both the public re-export
    (``aspose.threed.A3DObject``) and the submodule-qualified original
    (``aspose.threed.A3DObject.A3DObject``) must be among the 300 kept types."""
    data = _load_fixture()
    by_class_import = {entry["class_import"]: entry for entry in data["types"]}
    for class_import in ("aspose.threed.A3DObject", "aspose.threed.A3DObject.A3DObject"):
        assert class_import in by_class_import, class_import + " must be present among the kept types"
        entry = by_class_import[class_import]
        assert entry["name"] == "A3DObject"
        assert entry["kind"] == "class"
        assert entry["bases"] == ["INamedObject"]
        assert entry["file"].endswith(".py")


def test_a_real_inherited_member_carries_the_correct_inherited_from_tag() -> None:
    """TC-288/TC-293: the concrete proof this regenerated fixture closes the gap TC-288
    originally found (TC-281 made ``_flatten_inheritance()`` execute for Python, but its own
    short-name index still resolved every bare-name ``bases`` entry in this pilot to an empty
    re-export shell, so it copied zero members anywhere - until TC-293 fixed that index).
    ``AssetInfo`` genuinely declares ``bases == ["A3DObject"]`` (the bare, unqualified name, the
    way the real source actually writes it) and now really does inherit ``A3DObject``'s own
    real members, each tagged "inherited_from" the real, member-bearing definition
    (``aspose.threed.A3DObject.A3DObject``) - never the empty re-export shell
    (``aspose.threed.A3DObject``) that used to win this exact resolution before TC-293."""
    data = _load_fixture()
    by_class_import = {entry["class_import"]: entry for entry in data["types"]}
    asset_info = by_class_import["aspose.threed.AssetInfo.AssetInfo"]
    assert asset_info["bases"] == ["A3DObject"]

    inherited = {m["name"]: m for m in asset_info["methods"] if "inherited_from" in m}
    assert {"find_property", "get_property", "name", "properties", "remove_property", "set_property"} <= set(
        inherited
    )
    for member in inherited.values():
        assert member["inherited_from"] == "aspose.threed.A3DObject.A3DObject"


def test_a_real_transitively_inherited_member_is_rooted_to_the_real_grandparent() -> None:
    """A real, live multi-level chain confirmed directly against this fixture (not invented,
    mirroring TC-261's own pdf/cpp PopupAnnotation/Annotation/BaseParagraph proof): ``Node``
    declares ``bases == ["SceneObject"]`` (its direct parent only), and ``SceneObject`` itself
    declares ``bases == ["A3DObject"]``. ``find_property`` is genuinely declared by the
    grandparent ``A3DObject``, copied into ``SceneObject`` first (parents resolve before
    children), then copied again into ``Node`` - and must still be rooted to ``A3DObject``,
    the class that actually declares it, never to ``SceneObject``, the intermediate parent it
    passed through on the way."""
    data = _load_fixture()
    by_class_import = {entry["class_import"]: entry for entry in data["types"]}
    node = by_class_import["aspose.threed.Node.Node"]
    scene_object = by_class_import["aspose.threed.SceneObject.SceneObject"]
    assert node["bases"] == ["SceneObject"]
    assert scene_object["bases"] == ["A3DObject"]

    find_property = next(m for m in node["methods"] if m["name"] == "find_property")
    assert find_property["inherited_from"] == "aspose.threed.A3DObject.A3DObject"
    assert find_property["inherited_from"] != "aspose.threed.SceneObject.SceneObject"

    # Node's own genuinely-declared members must never carry the key.
    add_child_node = next(m for m in node["methods"] if m["name"] == "add_child_node")
    assert "inherited_from" not in add_child_node
