"""Offline tests against the committed pdf/java fixture - no network, no live clone.

``gatectl`` verifies this card with the network proxied to a dead port (TC-044 sets
``network: false``), so nothing here may reach out; everything is read from the fixture
``run_extraction.py`` already produced and committed at
``tests/fixtures/pdf_java/api_surface.json``.

Java's extraction path had never been exercised against a real cloned repository through
the actual extraction entrypoint before this card - unlike Go/Rust, which had at least
shallow synthetic coverage. It went through cleanly: ``java`` is an ordinary tree-sitter
platform (not special-cased like ``python``), routed through
``tree_sitter_engine.api_surface`` via the ``"java"`` grammar name.

The observed ``kind`` vocabulary among the reduced fixture is the tree-sitter Java
grammar's own node-type names: ``{"class_declaration", "enum_declaration",
"interface_declaration"}`` - Java's three top-level type-declaration forms (this
repository's committed public surface happens to contain no ``record`` or
``annotation_type_declaration`` entries in the reduced subset).

Regenerated by TC-256 at the project's actual intended cap: the live repository now has
1239 public types (it grew since TC-044's original 1158-type onboarding snapshot), and
this fixture was generated with the real default ``--max-types 300`` - not the stale,
undersized ``150`` that TC-044 originally carried. Selection is by
``run_extraction.reduce_fixture()``'s centrality score (TC-252), not alphabetical order,
so the 300 kept types are the ones most referenced by the rest of the surface, not
whichever 150 happened to sort first. ``truncated`` is ``True`` and
``reduced_type_count`` is 300, not the full 1239.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

FIXTURE = Path(__file__).parents[1] / "fixtures" / "pdf_java" / "api_surface.json"
MANIFEST = Path(__file__).parents[2] / "config" / "products" / "pdf" / "java.yaml"

_COMMIT_SHA = re.compile(r"^[0-9a-f]{40}$")


def _load_fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_the_fixture_parses_and_has_the_expected_shape() -> None:
    data = _load_fixture()
    assert isinstance(data, dict)
    assert isinstance(data["types"], list)
    assert data["language"] == "java"


def test_the_fixture_records_the_exact_source_commit_and_repository() -> None:
    data = _load_fixture()
    assert _COMMIT_SHA.match(data["source_commit"]), data["source_commit"]
    # Recorded from the real live clone that produced this fixture - re-verify by hand with
    # `git ls-remote https://github.com/aspose-pdf-foss/Aspose.PDF-FOSS-for-Java` if this ever
    # needs re-pinning; do not change it to make a test pass.
    assert data["source_commit"] == "736cedaa2922e4952f429364bdb9a4bbb1d97863"
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    assert data["source_repository"] == manifest["repository"]


def test_the_fixture_is_non_empty_and_records_real_truncation() -> None:
    data = _load_fixture()
    assert len(data["types"]) > 0
    assert data["reduced_type_count"] == len(data["types"])
    # Regenerated by TC-256: the live repository now has 1239 public types (grown since
    # TC-044's 1158), and this fixture was generated with the real default --max-types 300
    # (not the stale, undersized 150 TC-044 originally carried).
    assert data["type_count"] == 1239
    assert data["reduced_type_count"] == 300
    assert data["truncated"] is True


def test_the_fixture_contains_real_java_type_names() -> None:
    data = _load_fixture()
    names = {entry["name"] for entry in data["types"]}
    # Real Aspose.PDF-FOSS-for-Java exported types, not placeholders - would not survive an
    # empty or synthetic fixture. PageCollection is no longer among the top-300 kept by
    # centrality (TC-256's own re-run), so it is deliberately not asserted here - it is
    # still reachable as Document.getPages()'s return_type, see below.
    assert {"Document", "Page", "IAppointment", "HtmlSaveOptions"} <= names
    assert all(entry["file"].endswith(".java") for entry in data["types"])


def test_every_entry_is_a_real_java_surface_kind() -> None:
    data = _load_fixture()
    kinds = {entry["kind"] for entry in data["types"]}
    # Observed directly from the live tree-sitter Java grammar's own node-type vocabulary for
    # this repository, not guessed or invented: the reduced subset's public surface only
    # exercises these three of Java's top-level type-declaration forms.
    assert kinds == {"class_declaration", "enum_declaration", "interface_declaration"}


def test_common_fields_are_present_on_every_entry() -> None:
    data = _load_fixture()
    for entry in data["types"]:
        for key in (
            "name",
            "kind",
            "file",
            "line",
            "doc",
            "methods",
            "properties",
            "bases",
            "reachable",
            "visibility",
            "class_import",
            "canonical_namespace",
        ):
            assert key in entry, (entry.get("name"), key)


def test_a_real_class_a_real_interface_and_a_real_enum_are_present() -> None:
    data = _load_fixture()
    by_name = {entry["name"]: entry for entry in data["types"]}

    # Observed directly in the live run: Document is a real class that implements
    # java.io.Closeable and has a real getPages() accessor returning PageCollection.
    document = by_name["Document"]
    assert document["kind"] == "class_declaration"
    assert document["bases"] == ["Closeable"]
    methods = {m["name"]: m for m in document["methods"]}
    assert "getPages" in methods
    assert methods["getPages"]["return_type"] == "PageCollection"
    assert methods["getPages"]["is_constructor"] is False

    # IAppointment is a real marker interface with no methods of its own.
    interface = by_name["IAppointment"]
    assert interface["kind"] == "interface_declaration"
    assert interface["methods"] == []

    # HorizontalAlignment is a real enum with real members. (AntialiasingProcessingType, used
    # before TC-256's re-run, no longer survives the top-300 centrality cut; HorizontalAlignment
    # does, observed directly in this live run.)
    enum = by_name["HorizontalAlignment"]
    assert enum["kind"] == "enum_declaration"
    enum_member_names = {m["name"] for m in enum["enum_members"]}
    assert {"Left", "Right", "Center"} <= enum_member_names
