"""Offline tests against the committed slides/net fixture - no network, no live clone, no engine.

``gatectl`` verifies this card with the network proxied to a dead port (TC-159 sets
``network: false``), so nothing here may reach out; everything is read from the fixture
``run_extraction.py`` already produced and committed at
``tests/fixtures/slides_net/api_surface.json``.

TC-314 (2026-10-09): this fixture was last regenerated by TC-159, long before TC-252
(centrality-ranked ``reduce_fixture()``) or TC-261 (the C3 fix adding ``inherited_from``
provenance tagging) landed on main. It had real inheritance - 134 of 264 types with
non-empty ``bases`` - but carried zero ``inherited_from`` tags anywhere, the exact defect
TC-261 was supposed to close. A live re-run (both TC-252 and TC-261 confirmed on main first)
is a pure, purely-additive re-pin: same 264 types, same source commit
(``86c441b5d81e707f2ea9e01b197dbb6ff7a3859b``), zero structural change to any type beyond
580 real ``"inherited_from": "..."`` keys added to already-copied members. This is NOT the
TC-301/TC-303 "genuinely flat" case - slides/net has real, non-trivial base classes and the
live re-run proves it.

See ``test_a_real_inherited_member_carries_the_correct_inherited_from_tag`` below for a
genuine 4-level chain (``Table`` -> ``GraphicalObject`` -> ``Shape`` -> ``PVIObject``)
proving the tag is rooted to the real original declaring class, not an intermediate one
the member was copied through.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

FIXTURE = Path(__file__).parents[1] / "fixtures" / "slides_net" / "api_surface.json"
MANIFEST = Path(__file__).parents[2] / "config" / "products" / "slides" / "net.yaml"

_COMMIT_SHA = re.compile(r"^[0-9a-f]{40}$")


def _load_fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_the_fixture_parses_and_has_the_expected_shape() -> None:
    data = _load_fixture()
    assert isinstance(data, dict)
    assert isinstance(data["types"], list)
    assert data["language"] == "csharp"


def test_the_fixture_records_the_exact_source_commit_and_repository() -> None:
    data = _load_fixture()
    assert _COMMIT_SHA.match(data["source_commit"]), data["source_commit"]
    # Recorded from the real shallow clone that produced this fixture - re-verify by hand with
    # `git ls-remote https://github.com/aspose-slides-foss/Aspose.Slides-FOSS-for-.NET` if this
    # ever needs re-pinning; do not change it to make a test pass.
    assert data["source_commit"] == "86c441b5d81e707f2ea9e01b197dbb6ff7a3859b"
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    assert data["source_repository"] == manifest["repository"]
    assert data["source_repository"] == "aspose-slides-foss/Aspose.Slides-FOSS-for-.NET"


def test_the_fixture_is_non_empty() -> None:
    data = _load_fixture()
    assert len(data["types"]) > 0
    assert data["reduced_type_count"] == len(data["types"])
    assert data["type_count"] >= data["reduced_type_count"]
    # The real repository has 264 public types, under the real default --max-types 300 cap,
    # so nothing is truncated.
    assert data["type_count"] == 264
    assert data["truncated"] is False


def test_the_fixture_contains_real_dotnet_type_names() -> None:
    data = _load_fixture()
    names = {entry["name"] for entry in data["types"]}
    # Real Aspose.Slides types, not placeholders - would not survive an empty or synthetic fixture.
    assert {"AutoShape", "BulletType", "BaseSlide", "Table", "Shape"} <= names
    assert all(entry.get("class_import", "").startswith("Aspose.Slides") for entry in data["types"])
    assert all(entry["file"].endswith(".cs") for entry in data["types"])


def test_every_entry_is_a_real_csharp_declaration_kind() -> None:
    data = _load_fixture()
    kinds = {entry["kind"] for entry in data["types"]}
    assert kinds <= {
        "class_declaration",
        "struct_declaration",
        "interface_declaration",
        "enum_declaration",
        "record_declaration",
    }
    assert kinds


def test_real_inheritance_is_present_and_was_actually_flattened() -> None:
    # TC-314's starting premise, verified live: plenty of real non-trivial inheritance
    # (unlike the genuinely-flat TC-301/TC-303 siblings), and _flatten_inheritance() actually
    # copied members down from bases rather than leaving every subclass's own member list empty.
    data = _load_fixture()
    by_name = {entry["name"]: entry for entry in data["types"]}
    types_with_bases = [t for t in data["types"] if t.get("bases")]
    assert len(types_with_bases) >= 100

    total_inherited_tags = sum(
        1
        for t in data["types"]
        for m in t.get("methods", []) + t.get("properties", [])
        if m.get("inherited_from")
    )
    # 580 real copied members carry the tag (verified live during this card's run).
    assert total_inherited_tags == 580

    table = by_name["Table"]
    assert table["bases"] == ["GraphicalObject", "ITable"]
    table_members = {m["name"]: m for m in table["methods"] + table["properties"]}
    assert "X" in table_members
    assert table_members["X"].get("inherited_from")


def test_a_real_inherited_member_carries_the_correct_inherited_from_tag() -> None:
    # TC-314's headline assertion: this fixture's real inheritance predates TC-261's
    # inherited_from provenance fix, so before this regeneration every copied member was
    # untagged. This test picks one genuine multi-level chain and proves the tag is rooted to
    # the real ORIGINAL declaring class, not an intermediate one the member was copied
    # through - the same shape TC-261 itself required proof of.
    #
    # Real chain (all four classes genuinely exist in the pinned upstream source):
    #   Table -> GraphicalObject -> Shape -> PVIObject (-> ISlideComponent)
    # Shape itself genuinely declares X/Y/Width/Height (own file, own line, no
    # inherited_from). GraphicalObject's copy is correctly tagged back to Shape. Table
    # inherits X transitively THROUGH GraphicalObject, but the tag must stay rooted to
    # Shape - the real original declarer - not the intermediate GraphicalObject it was
    # copied through.
    data = _load_fixture()
    by_name = {entry["name"]: entry for entry in data["types"]}

    def member(type_name: str, member_name: str) -> dict:
        entry = by_name[type_name]
        for m in entry["methods"] + entry["properties"]:
            if m["name"] == member_name:
                return m
        raise AssertionError(f"{member_name} not found on {type_name}")

    shape = by_name["Shape"]
    assert shape["bases"] == ["PVIObject", "IShape"]
    shape_x = member("Shape", "X")
    # X is genuinely declared by Shape itself - no inherited_from key, real file/line.
    assert "inherited_from" not in shape_x
    assert shape_x["file"] == "src/Aspose.Slides.Foss/Shape.cs"

    graphical_object = by_name["GraphicalObject"]
    assert "Shape" in graphical_object["bases"]
    go_x = member("GraphicalObject", "X")
    assert go_x["inherited_from"] == "Aspose.Slides.Foss.Shape"

    table = by_name["Table"]
    assert "GraphicalObject" in table["bases"]
    assert "Shape" not in table["bases"]  # confirms X really is inherited transitively
    table_x = member("Table", "X")
    # Table inherits X through GraphicalObject, but the tag stays rooted to Shape - the
    # real original declarer - not the intermediate GraphicalObject.
    assert table_x["inherited_from"] == "Aspose.Slides.Foss.Shape"
    assert table_x["file"] == shape_x["file"]

    # One level further still: PVIObject (Shape's own base) genuinely declares Slide/
    # Presentation. Shape's copy is rooted to PVIObject; Table inherits them transitively
    # through TWO intermediate classes (GraphicalObject and Shape) yet the tag stays
    # rooted all the way back to PVIObject.
    pvi_object = by_name["PVIObject"]
    pvi_slide = member("PVIObject", "Slide")
    assert "inherited_from" not in pvi_slide

    shape_slide = member("Shape", "Slide")
    assert shape_slide["inherited_from"] == "Aspose.Slides.Foss.PVIObject"

    table_slide = member("Table", "Slide")
    assert table_slide["inherited_from"] == "Aspose.Slides.Foss.PVIObject"
